### ISSUE TITLE
"pecl install zip" fails

### ISSUE THREAD

**Issue by aripringle** [pierrejoye/php_zip#11]
As of the 1.13.0 release, I can't install this package using pecl. I've tested this on a CentOS 6 system running PHP 5.5.27 and a Debian system running PHP 5.6.13. I can still install the 1.12.5 release successfully. I get the following error:

    make: *** No rule to make target '/tmp/pear/temp/zip/php_zip.c', needed by 'php_zip.lo'.  Stop.

Here's full output:

pecl install zip
downloading zip-1.13.0.tgz ...
Starting to download zip-1.13.0.tgz (312,531 bytes)
.........done: 312,531 bytes
118 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
building in /tmp/pear/temp/pear-build-defaultuserkRfp7a/zip-1.13.0
running: /tmp/pear/temp/zip/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for zip archive read/writesupport... yes, shared
checking for the location of libz... no
checking pcre install prefix... no
checking libzip... no
checking for the location of zlib... /usr
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking fts.h usability... yes
checking fts.h presence... yes
checking for fts.h... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for ssize_t... yes
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of off_t... 8
checking size of size_t... 8
checking for touch... /usr/bin/touch
checking for unzip... no
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
make: *** No rule to make target '/tmp/pear/temp/zip/php_zip.c', needed by 'php_zip.lo'.  Stop.
ERROR: `make' failed

**Comment by remicollet** [comment]
Can you test if dd594c3fed5713512fb99d975899bb030f9808a7 fix this issue.

from a git clone of this repo

     pecl package
     pecl install /path/to/zip-1.13.0.tgz

**Comment by aripringle** [comment]
That seems to have taken care of it. Thank you!

**Comment by remicollet** [comment]
zip 1.13.1 is released, should install cleanly.

**Comment by aripringle** [comment]
Sorry, I should have tested on both of my systems. It installs fine on my CentOS system w/ PHP 5.5.27, but my Debian system (running PHP 5.6.13 in a docker container) is now failing with a new error. Full output below:

pecl install zip
downloading zip-1.13.1.tgz ...
Starting to download zip-1.13.1.tgz (312,567 bytes)
.................................................................done: 312,567 bytes
118 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
building in /tmp/pear/temp/pear-build-defaultuserRDvylc/zip-1.13.1
running: /tmp/pear/temp/zip/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for zip archive read/writesupport... yes, shared
checking for the location of libz... no
checking pcre install prefix... no
checking libzip... no
checking for the location of zlib... /usr
checking PHP version... PHP 5.x
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking fts.h usability... yes
checking fts.h presence... yes
checking for fts.h... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for ssize_t... yes
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of off_t... 8
checking size of size_t... 8
checking for touch... /usr/bin/touch
checking for unzip... no
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuserRDvylc/zip-1.13.1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/zip -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserRDvylc/zip-1.13.1/include -I/tmp/pear/temp/pear-build-defaultuserRDvylc/zip-1.13.1/main -I/tmp/pear/temp/zip -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/zip/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/zip/php5/php_zip.c -o php5/php_zip.lo
/tmp/pear/temp/pear-build-defaultuserRDvylc/zip-1.13.1/libtool: line 1283: php5/php_zip.loT: No such file or directory
mkdir php5/.libs
mkdir: cannot create directory 'php5/.libs': No such file or directory
Makefile:181: recipe for target 'php5/php_zip.lo' failed
make: *** [php5/php_zip.lo] Error 1
ERROR: `make' failed

**Comment by remicollet** [comment]
I've unreleased the 1.13.1

Please try from the git snapshot on debian, should be fixed by 041e4fb3a7984381ef7eba3772629b0da3456da4

I will release 1.13.1 after your test.

**Comment by aripringle** [comment]
Still looks like the same error from a fresh clone. I confirmed that your change in 041e4fb is present in the package I'm trying to install. Let me know if you need any more information about the system I'm trying it on. Here's the error:

running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuserVLMuU3/zip-1.13.1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/zip -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserVLMuU3/zip-1.13.1/include -I/tmp/pear/temp/pear-build-defaultuserVLMuU3/zip-1.13.1/main -I/tmp/pear/temp/zip -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/zip/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/zip/php5/php_zip.c -o php5/php_zip.lo
/tmp/pear/temp/pear-build-defaultuserVLMuU3/zip-1.13.1/libtool: line 1283: php5/php_zip.loT: No such file or directory
mkdir php5/.libs
mkdir: cannot create directory 'php5/.libs': No such file or directory
Makefile:181: recipe for target 'php5/php_zip.lo' failed
make: *** [php5/php_zip.lo] Error 1
ERROR: `make' failed

**Comment by remicollet** [comment]
Sorry, try again with d5191679675fa86464b7994da809d09cd365c084

**Comment by aripringle** [comment]
Looks like it is now installing successfully on both systems. Thank you!

**Comment by remicollet** [comment]
thanks for the feedback, and tests.

**Comment by remicollet** [comment]
And just FYI, for CentOS, I hope you know binary packages exists in some good 3rd party repository, such as http://rpms.remirepo.net/ which can avoid you to rebuild everything.
