### ISSUE TITLE
Zip archive created with files in local code-page, instead of UTF

### ISSUE THREAD

**Issue by SlavikCA** [pierrejoye/php_zip#12]
System: Ubuntu 14.04, PHP 5.6.16
Zip version	1.12.5

I created archive from my PHP script and all filenames stored in some code-page. I think in CP866.
```php
$zip->open($fileName, ZIPARCHIVE::CREATE)
```
I was expecting, that as of 1.11.0 filenames would be created in UTF.

Am I missing some flags to enforce UTF?

**Comment by SlavikCA** [comment]
Also, today tried to test with this system:
- PHP 7.0.0
- Ubuntu 14.04
- Zip version	1.13.0
- Libzip version	1.0.1

Same results. Archive created with filenames stored not in UTF-8.

```php
<?php
$zip = new ZipArchive();
if ($zip->open("test.zip", ZIPARCHIVE::CREATE) !== true)
    die ("Failed to create archive");

if (!$zip->addFile("/var/www/test/web/тест123")) //here are UTF-8 characters in the filename
    print ("Failure adding file");

$zip->close();
```

**Comment by sergey-dryabzhinsky** [comment]
How did you check that archive uses wrong code-page for stored file names?
I tried your code in console and:
```
$ unzip -l test.zip 
Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2016-04-29 04:18   тест123
---------                     -------
        0                     1 file
```

**Comment by pierrejoye** [comment]
Hi

It is your responsibility to pass UTF-8 (common on linux) on Linux or other
encoding matching your system while I am pretty sure no linux filesysyems
care about it.

**Comment by pierrejoye** [comment]
To detect encoding you may use the mbstring functions.

**Comment by SlavikCA** [comment]
As I spent more time - I found it actually working, as expected - generating zip files with UTF-8 filenames.
The problem was, that Win7 can't unzip such files correctly. The issue was fixed in Win8.
