### ISSUE TITLE
getStream() name is inconsistent with other methods

### ISSUE THREAD

**Issue by DennisBirkholz** [pierrejoye/php_zip#20]
To parallel other method naming, there should be a `getStreamName(string $name, int $flags)` and a `getStreamIndex(int $index, int $flags)` method. In addition, `getStream()` does not accept flags but could accept `ZipArchive::FL_UNCHANGED`, `ZipArchive::FL_NOCASE`, `ZipArchive::FL_NODIR` (like `locateName()`) and `ZipArchive::FL_COMPRESSED` if it is possible to access the uncompressed stream by libzip.

**Comment by remicollet** [comment]
Working on it

**Comment by remicollet** [comment]
WIP in https://github.com/php/php-src/pull/7558
