### ISSUE TITLE
php_zip under Mac Big Sur cannot be install for php7.3 and php7.4

### ISSUE THREAD

**Issue by nise** [pierrejoye/php_zip#30]
Using `pecl install zip` it says that the "No releases available for package "pecl.php.net/zip"

If I try to install it from the latest tarball I can run the installation which states to be successful. In the php.ini or in the PHP info no zip extension will be listed. Also if I add 

`extension="/opt/homebrew/Cellar/php@7.3/7.3.33_2/pecl/20180731/zip.so"` or just `extension=zip.so` it is not working.

Of course I've restarted apache after the installation and php.ini changes.

See also my post here: https://stackoverflow.com/questions/65228419/zip-extension-needs-to-be-loaded-for-opencart-macos-big-sur/72492775#72492775

Any help is welcome.

**Comment by cmb69** [comment]
> Using `pecl install zip` it says that the "No releases available for package "pecl.php.net/zip"

Hmm, this doesn't like an issue with this package, since [releases are available](http://pecl.php.net/zip). It might be  a homebrew issue, or maybe you just need to update the channel list (`pecl update-channels`).

> If I try to install it from the latest tarball I can run the installation which states to be successful. In the php.ini or in the PHP info no zip extension will be listed.

Possibly, libzip can't be found; check LD_LIBRARY_PATH.

**Comment by nise** [comment]
Thanks for the hints. Finally, I was using the wrong PHP executable that was not linked with PHP zip. See https://stackoverflow.com/questions/13613313/osx-apache-using-wrong-version-of-php
