### ISSUE TITLE
Failure closing ZIP files post upgrade to latest pecl-zip 1.22.0 (from remi repo)

### ISSUE THREAD

**Issue by shimile** [pierrejoye/php_zip#34]
I wanted to provide with a reproducer code, but unfortunately, a minimal test case does not fail like my whole system does.

The code collects hundreds (maybe > thousand) files into a ZIP, and since the upgrade mentioned in the issue title above (that came along with an upgrade of libzip5 to version 1.10.0) - $zip->close() returns an error, where $zip->getStatusString() returns the message: "Unexpected length of data", and the ZIP file is gone.

I went along to dig in libzip, and found that this message was added in libzip5 v1.10.0:
```diff -ru libzip-1.9.2/lib/zip.h libzip-1.10.0/lib/zip.h
--- libzip-1.9.2/lib/zip.h      2022-06-28 17:17:12.000000000 +0300
+++ libzip-1.10.0/lib/zip.h     2023-06-23 17:27:16.000000000 +0300
@@ -58,6 +58,16 @@
 #endif
 #endif
 
+#ifndef ZIP_DEPRECATED
+#if defined(__GNUC__) || defined(__clang__)
+#define ZIP_DEPRECATED(x) __attribute__((deprecated(x)))
+#elif defined(_MSC_VER)
+#define ZIP_DEPRECATED(x) __declspec(deprecated(x))
+#else
+#define ZIP_DEPRECATED(x)
+#endif
+#endif
+
 #include <stdio.h>
 #include <sys/types.h>
 #include <time.h>
@@ -77,7 +87,7 @@
 #define ZIP_FL_NODIR 2u        /* ignore directory component */
 #define ZIP_FL_COMPRESSED 4u   /* read compressed data */
 #define ZIP_FL_UNCHANGED 8u    /* use original data, ignoring changes */
-#define ZIP_FL_RECOMPRESS 16u  /* force recompression of data */
+/* 16u was ZIP_FL_RECOMPRESS, which is deprecated */
 #define ZIP_FL_ENCRYPTED 32u   /* read encrypted data (implies ZIP_FL_COMPRESSED) */
 #define ZIP_FL_ENC_GUESS 0u    /* guess string encoding (is default) */
 #define ZIP_FL_ENC_RAW 64u     /* get unmodified string */
@@ -91,7 +101,10 @@
 
 /* archive global flags flags */
 
-#define ZIP_AFL_RDONLY 2u /* read only -- cannot be cleared */
+#define ZIP_AFL_RDONLY  2u /* read only -- cannot be cleared */
+#define ZIP_AFL_IS_TORRENTZIP  4u /* current archive is torrentzipped */
+#define ZIP_AFL_WANT_TORRENTZIP        8u /* write archive in torrentzip format */
+#define ZIP_AFL_CREATE_OR_KEEP_FILE_FOR_EMPTY_ARCHIVE 16u /* don't remove file if archive is empty */
 
 
 /* create a new extra field */
@@ -135,6 +148,8 @@
 #define ZIP_ER_TELL 30            /* S Tell error */
 #define ZIP_ER_COMPRESSED_DATA 31 /* N Compressed data invalid */
 #define ZIP_ER_CANCELLED 32       /* N Operation cancelled */
+#define ZIP_ER_DATA_LENGTH 33     /* N Unexpected length of data */
```

And:

```diff -ru libzip-1.9.2/lib/zip_source_crc.c libzip-1.10.0/lib/zip_source_crc.c
--- libzip-1.9.2/lib/zip_source_crc.c   2022-06-28 17:17:12.000000000 +0300
+++ libzip-1.10.0/lib/zip_source_crc.c  2023-06-23 17:27:16.000000000 +0300
@@ -141,6 +141,10 @@
         st = (zip_stat_t *)data;
 
         if (ctx->crc_complete) {
+            if ((st->valid & ZIP_STAT_SIZE) && st->size != ctx->size) {
+                zip_error_set(&ctx->error, ZIP_ER_DATA_LENGTH, 0);
+                return -1;
+            }
```

So obviously, that code could not have failed with that error previously.

The problem I have now - is - how to narrow down the failure to 'which file of the files I am adding to the ZIP is causing this'? - to see if I can workaround it; Assuming, at all, the issue is on my side (like, a file  that is changing while it is zipped?) - or simply a bug in the library that gets exposed now due to the new test in the code... or... that the test itself is flawed...

If only the status message said which path or ID or anything query-able on the zip object is the cause of the failure, it would be quite helpful...

**Comment by remicollet** [comment]
> or simply a bug in the library

Probably worth to report it on https://github.com/nih-at/libzip/issues
as there is no real change in this extension (only new constants and new methods, but without any other changes)

**Comment by remicollet** [comment]
possible way to find the file raising the bug, close (flush) the archive after each add, and reopen it

**Comment by shimile** [comment]
'feature' introduced by upstream v1.10.0: if any of the files you have added to a zip changes while zip is being closed, zip fails and the archive is gone.

**Comment by remicollet** [comment]
Waiting for upstream proper solution 
Can you try a workaround to add the file with its size

`$zip->addFile($path, $name, 0, filesize($path));`

**Comment by remicollet** [comment]
IIRC it won't try to read more than given size, so should find expected length... perhaps...

BTW, hard for me to reproduce (and don't want to run such test on some prod server with active logs)

**Comment by shimile** [comment]
OK, I'll try, but then comes the question: What if by the time libzip fopen()s it, the log is rotated and becomes smaller :)

Is it 'read at most N bytes' or 'read N bytes' and fail if you reached EOF earlier

**Comment by remicollet** [comment]
> Is it 'read at most N bytes' or 'read N bytes' and fail if you reached EOF earlier

undocumented ;)
https://libzip.org/documentation/zip_source_file.html

**Comment by remicollet** [comment]
FYI, I'm unable to reproduce on an active server, using
```
<?php
$log = "/var/log/httpd/access_log";
var_dump(filesize($log));
$z = new ZipArchive();
$z->open("/tmp/foo.zip", ZipArchive::CREATE);
$z->registerProgressCallback(0.05, function ($r) {
static $deb=0;
if ($deb==0) $deb=microtime(true);
printf("%.3f: %d%%\n", microtime(true)-$deb, (int)($r * 100));
});
$z->addFile($log, "access.log");
var_dump($z->close(), $z->status);
var_dump(filesize($log));
```

Output is (and the log has grow)
```
int(655383700)
0.000: 0%
11.541: 5%
15.474: 100%
bool(true)
int(0)
int(655620529)
```

**Comment by remicollet** [comment]
> maybe PHP can have addFile fopen the file for zip and pass the file pointer to libzip so such hack won't be needed...

No, as explained, it will consume far too much file descriptors.

BTW, I can imagine a new method  `addStream($fp)`, but it won't work because of double close... (one in libzip, one in php stream management)

**Comment by remicollet** [comment]
> and your server has libzip5-1.10.0-1.el7.remi.x86_64

I'm not using CentOS 7 which is close to its EOF in a few months :p
(so using libzip-1.10.0-1.el8.remi.x86_64 on CentOS Stream 8)

I recommend to plan an upgrade ASAP ;)

>  (and php restarted to load the new code)?

No, running from cli

**Comment by shimile** [comment]
That's OK, I'm also working on upgrading to CentOS Stream 9 :)

Then I have no idea why you can't reproduce. Based on libzip's comments, the fact that you can't reproduce - is a bug ;). But it reproduces for me 100% of the time, when when I downgrade back the RPM of libzip and pecl-php to the versions the system had yesterday, it reproduces 0% of the time for me...

**Comment by remicollet** [comment]
notice (unrelated to this issue, but about file disappearing before archive close)

Next version (1.22.1) will have a` ZipArchive::FL_OPEN_FILE_NOW ` to avoid this
See https://github.com/pierrejoye/php_zip/blob/master/tests/oo_addfile.phpt for usage

Test/feedback welcome

**Comment by shimile** [comment]
> notice (unrelated to this issue, but about file disappearing before archive close)
> 
> Next version (1.22.1) will have a`ZipArchive::FL_OPEN_FILE_NOW` to avoid this See https://github.com/pierrejoye/php_zip/blob/master/tests/oo_addfile.phpt for usage
> 
> Test/feedback welcome

That is awesome, thanks! I'll be able to remove so many lines of hacky code around this limitation. Yes, I am aware of the increase in open file descriptors - and am willing to 'pay the price' for the extra stability and code readability. Thanks for seeing the real world need - as long as the behavior ("take notice of your ulimit etc") is documented, I am sure other people will appreciate it too!

I do have a feedback/question: So if you will call addFile with `ZipArchive::FL_OPEN_FILE_NOW` and the file _already does not exist by the time  this method is called_ (e.g. I was doing readdir() and then doing addFile one by one, and by the time addFile does its' think, the file is already gone) - will addFile method now _return an error_?

Question 2 which is why I was confused about this to begin with: https://www.php.net/manual/en/ziparchive.addfile.php has a note saying: 
"When a file is set to be added to the archive, PHP will lock the file. The lock is only released once the [ZipArchive](https://www.php.net/manual/en/class.ziparchive.php) object has been closed, either via [ZipArchive::close()](https://www.php.net/manual/en/ziparchive.close.php) or the [ZipArchive](https://www.php.net/manual/en/class.ziparchive.php) object being destroyed. This may prevent you from being able to delete the file being added until after the lock has been released."

Isn't that an invalid statement, giving what we know? I mean, maybe during close(), but... "when a file is set to be added"? If that was true, there would be no need for ZipArchive::FL_OPEN_FILE_NOW, no?

Thanks!!!

**Comment by remicollet** [comment]
> I do have a feedback/question: So if you will call addFile with `ZipArchive::FL_OPEN_FILE_NOW` and the file _already does not exist by the time this method is called_ (e.g. I was doing readdir() and then doing addFile one by one, and by the time addFile does its' think, the file is already gone) - will addFile method now _return an error_?

Yes, addFile will fail.

> Question 2 which is why I was confused about this to begin with: https://www.php.net/manual/en/ziparchive.addfile.php has a note saying: "When a file is set to be added to the archive, PHP will lock the file. The lock is only released once the [ZipArchive](https://www.php.net/manual/en/class.ziparchive.php) object has been closed, either via [ZipArchive::close()](https://www.php.net/manual/en/ziparchive.close.php) or the [ZipArchive](https://www.php.net/manual/en/class.ziparchive.php) object being destroyed. This may prevent you from being able to delete the file being added until after the lock has been released."
> 
> Isn't that an invalid statement, giving what we know? I mean, maybe during close(), but... "when a file is set to be added"? If that was true, there would be no need for ZipArchive::FL_OPEN_FILE_NOW, no?

Doc is outdated, will be fixed later

**Comment by remicollet** [comment]
BTW, it seems some kind of lock exists on Windows... 
=> https://github.com/php/php-src/pull/11556

**Comment by shimile** [comment]
> BTW, it seems some kind of lock exists on Windows... => [php/php-src#11556](https://github.com/php/php-src/pull/11556)

I assumed from the beginning that the lock mentioned is in Windows - after all you can't _really_ lock a file in Linux, i.e. it is advisory and won't affect someone who is not actively looking for the so-called 'lock'. But yeah, I guess you can do advisory lock in Linux too... it won't usually do anything, but...

I am not really an expert in all things Windows, but I think that if a file is opened with FILE_SHARE_DELETE then it can later be deleted after open...
