### ISSUE TITLE
zip.so not working with PHP 8.1.12

### ISSUE THREAD

**Issue by atriummatt** [pierrejoye/php_zip#35]
My team has been trying to use pecl to install the zip package on Amazon Linux 2023, since there is currently no official php81-zip package planned for that distro.

Following these steps:
`sudo yum install php8.1-devel php-pear libzip libzip-devel`
`sudo pecl install zip`
`echo "extension=zip.so" | sudo tee /etc/php.d/20-zip.ini`
`sudo service php-fpm restart`

The steps all appear to run without errors, but the resulting `zip.so` extension throws an **undefined symbol: php_pcre2_match** error when we try to use it in PHP:
`$ php -v`
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20210903/zip.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210903/zip.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210903/zip.so: undefined symbol: php_pcre2_match), /usr/lib64/php/modules//usr/local/lib/php/extensions/no-debug-non-zts-20210903/zip.so.so (/usr/lib64/php/modules//usr/local/lib/php/extensions/no-debug-non-zts-20210903/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

Are we missing any dependencies for the installation?

We have tried installing previous versions of the package, and have also tried downloading the zip-1.22.1.tgz file manually and making the extension, but it still results in the same error when trying to use the zip.so extension with PHP.

**OS version:** Amazon Linux 2023 (2022.0.20230118)
**PHP version:**
PHP 8.1.12 (cli) (built: Oct 25 2022 17:30:00) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies

No other versions of PHP are currently installed.

**Comment by remicollet** [comment]
Cannot reproduce 

```
$ podman run --rm -ti amazonlinux:2023 /bin/bash
# dnf install php8.1-cli php-pear php8.1-devel libzip-devel
# pecl install zip
# echo "extension=zip" >/etc/php.d/20-zip.ini

# php -v
PHP 8.1.14 (cli) (built: Jan  4 2023 17:23:14) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies

# php --ri zip

zip

Zip => enabled
Zip version => 1.22.1
Libzip version => 1.7.3
```

> /usr/local/lib/php/extensions/no-debug-non-zts-20210903/zip.so

Looks like you are using a manually build PHP
Check pcre extension is enabled
