### ISSUE TITLE
Windows DLL available to download

### ISSUE THREAD

**Issue by macintoshplus** [pierrejoye/php_zip#38]
I am pleased to announce that this extension is now compiled for Windows by the PHP Extension Repository site.

You can download the DLLs on the extension page: https://phpext.phptools.online/extension/file-formats/zip-318

If you have any questions, I am available to discuss them.

**Comment by cmb69** [comment]
Due to https://github.com/php/php-windows-builder, the official Windows builds of PECL extensions are back; in this case see https://pecl.php.net/package/zip.

Anyhow, such announcements are non-actionable issues, thus I'm closing this ticket as "invalid".
